const WA="https://chat.whatsapp.com/GYyW35sRFnK48pLdCQGMdv?mode=gi_t";
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json;charset=UTF-8","cache-control":"no-store"}});
const html=x=>new Response(x,{headers:{"content-type":"text/html;charset=UTF-8","cache-control":"no-store"}});
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function list(env){const x=await env.TRACKER.get("participants","json");return Array.isArray(x)?x:[]}
async function save(env,x){await env.TRACKER.put("participants",JSON.stringify(x))}
function page(body){return `<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Competition Tracker</title><style>body{font-family:system-ui;max-width:900px;margin:30px auto;padding:0 16px;background:#f6f7fb;color:#151515}main{background:white;padding:22px;border-radius:16px}input,button{padding:11px;margin:4px;border:1px solid #ddd;border-radius:9px}button{cursor:pointer;font-weight:700}table{width:100%;border-collapse:collapse;margin-top:18px}td,th{padding:10px;border-bottom:1px solid #eee;text-align:left}.muted{color:#666;font-size:14px}code{word-break:break-all}</style><main>${body}</main>`}
export default{async fetch(req,env){const u=new URL(req.url),p=u.pathname;
if(p==="/")return Response.redirect(u.origin+"/admin",302);
if(p.startsWith("/r/")){const code=decodeURIComponent(p.slice(3));let ps=await list(env),i=ps.findIndex(x=>x.code===code&&x.active!==false);if(i<0)return new Response("Lien inconnu",{status:404});let x=ps[i];x.clicks=(x.clicks||0)+1;const ip=req.headers.get("CF-Connecting-IP")||"unknown";const day=new Date().toISOString().slice(0,10),k=`u:${code}:${day}:${ip}`;if(!await env.TRACKER.get(k)){x.unique=(x.unique||0)+1;await env.TRACKER.put(k,"1",{expirationTtl:172800})}ps[i]=x;await save(env,ps);return Response.redirect(x.destination||WA,302)}
if(p==="/api/add"&&req.method==="POST"){const f=await req.formData(),name=String(f.get("name")||"").trim(),code=String(f.get("code")||"").trim().toLowerCase().replace(/[^a-z0-9_-]/g,""),destination=String(f.get("destination")||WA).trim();if(!name||!code)return json({error:"name/code requis"},400);let ps=await list(env);if(ps.some(x=>x.code===code))return json({error:"code déjà utilisé"},409);ps.push({name,code,destination,clicks:0,unique:0,active:true});await save(env,ps);return Response.redirect(u.origin+"/admin",303)}
if(p==="/api/delete"&&req.method==="POST"){const f=await req.formData(),code=String(f.get("code")||"");let ps=await list(env);ps=ps.filter(x=>x.code!==code);await save(env,ps);return Response.redirect(u.origin+"/admin",303)}
if(p==="/api/stats")return json(await list(env));
if(p==="/admin"){let ps=(await list(env)).sort((a,b)=>(b.unique||0)-(a.unique||0));let rows=ps.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td><code>${esc(u.origin+"/r/"+x.code)}</code></td><td>${x.clicks||0}</td><td><b>${x.unique||0}</b></td><td><form method=post action=/api/delete><input type=hidden name=code value="${esc(x.code)}"><button>Supprimer</button></form></td></tr>`).join("");return html(page(`<h1>🏆 Competition Link Tracker</h1><p class=muted>Crée autant de participants que nécessaire. Chaque lien redirige vers WhatsApp et compte clics + visiteurs uniques.</p><form method=post action=/api/add><input name=name placeholder="Nom du participant" required><input name=code placeholder="Code: p1, tonny..." required><input name=destination style="min-width:320px" value="${esc(WA)}" required><button>+ Créer le lien</button></form><table><thead><tr><th>#</th><th>Participant</th><th>Lien</th><th>Clics</th><th>Uniques</th><th></th></tr></thead><tbody>${rows||"<tr><td colspan=6>Aucun participant.</td></tr>"}</tbody></table>`))}
return new Response("Not found",{status:404})}};