const WA_DEFAULT="https://chat.whatsapp.com/GYyW35sRFnK48pLdCQGMdv?mode=gi_t";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function getState(){try{const r=await fetch(process.env.KV_REST_API_URL+"/get/state",{headers:{Authorization:"Bearer "+process.env.KV_REST_API_TOKEN}});const j=await r.json();return j.result?JSON.parse(j.result):[]}catch{return[]}}
async function setState(x){await fetch(process.env.KV_REST_API_URL+"/set/state",{method:"POST",headers:{Authorization:"Bearer "+process.env.KV_REST_API_TOKEN","Content-Type":"application/json"},body:JSON.stringify(x)})}
async function seen(k){const r=await fetch(process.env.KV_REST_API_URL+"/set/"+encodeURIComponent(k)+"/1?nx=true&ex=172800",{method:"POST",headers:{Authorization:"Bearer "+process.env.KV_REST_API_TOKEN}});const j=await r.json();return j.result==="OK"}
function send(res,status,body,type="text/html; charset=utf-8"){res.status(status).setHeader("Content-Type",type).setHeader("Cache-Control","no-store").send(body)}
export default async function handler(req,res){const path=(req.query.path||[]).join("/"),origin="https://"+req.headers.host;
if(path.startsWith("r/")){const code=decodeURIComponent(path.slice(2)),ps=await getState(),i=ps.findIndex(x=>x.code===code&&x.active!==false);if(i<0)return send(res,404,"Lien inconnu","text/plain");ps[i].clicks=(ps[i].clicks||0)+1;const ip=(req.headers["x-forwarded-for"]||"unknown").split(",")[0],day=new Date().toISOString().slice(0,10);if(await seen("u:"+code+":"+day+":"+ip))ps[i].unique=(ps[i].unique||0)+1;await setState(ps);res.writeHead(302,{Location:ps[i].destination||WA_DEFAULT});return res.end()}
if(path==="api/add"&&req.method==="POST"){let ps=await getState(),name=String(req.body?.name||"").trim(),code=String(req.body?.code||"").trim().toLowerCase().replace(/[^a-z0-9_-]/g,""),destination=String(req.body?.destination||WA_DEFAULT).trim();if(!name||!code)return send(res,400,"Nom/code requis","text/plain");if(ps.some(x=>x.code===code))return send(res,409,"Code déjà utilisé","text/plain");ps.push({name,code,destination,clicks:0,unique:0,active:true});await setState(ps);res.writeHead(303,{Location:"/admin"});return res.end()}
if(path==="api/delete"&&req.method==="POST"){let ps=(await getState()).filter(x=>x.code!==String(req.body?.code||""));await setState(ps);res.writeHead(303,{Location:"/admin"});return res.end()}
if(path==="api/stats")return send(res,200,JSON.stringify(await getState()),"application/json; charset=utf-8");
if(path===""||path==="admin"){const configured=!!(process.env.KV_REST_API_URL&&process.env.KV_REST_API_TOKEN);let ps=(await getState()).sort((a,b)=>(b.unique||0)-(a.unique||0));const rows=ps.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td><code>${esc(origin+"/r/"+x.code)}</code></td><td>${x.clicks||0}</td><td><b>${x.unique||0}</b></td><td><form method=post action=/api/delete><input type=hidden name=code value="${esc(x.code)}"><button>Supprimer</button></form></td></tr>`).join("");return send(res,200,`<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><title>Competition Tracker</title><style>body{font-family:system-ui;max-width:1000px;margin:30px auto;padding:0 16px;background:#f5f7fb;color:#111}main{background:#fff;padding:24px;border-radius:18px;box-shadow:0 8px 30px #0001}input,button{padding:11px;margin:4px;border:1px solid #ddd;border-radius:9px}button{font-weight:700;cursor:pointer}table{width:100%;border-collapse:collapse;margin-top:18px}td,th{padding:10px;border-bottom:1px solid #eee;text-align:left}code{word-break:break-all}.warn{padding:12px;background:#fff3cd;border-radius:10px}</style><main><h1>🏆 Competition Link Tracker</h1>${configured?"":'<p class=warn>⚠️ Stockage non configuré : ajoute KV_REST_API_URL et KV_REST_API_TOKEN dans Vercel.</p>'}<p>Ajoute autant de participants que nécessaire. Classement par visiteurs uniques.</p><form method=post action=/api/add><input name=name placeholder="Nom du participant" required><input name=code placeholder="Code: p1, tonny..." required><input name=destination style="min-width:320px" value="${esc(WA_DEFAULT)}" required><button>+ Créer le lien</button></form><table><tr><th>#</th><th>Participant</th><th>Lien</th><th>Clics</th><th>Uniques</th><th></th></tr>${rows||"<tr><td colspan=6>Aucun participant.</td></tr>"}</table></main>`)}
return send(res,404,"Not found","text/plain")}